plugins {
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'dev.architectury.loom' version '1.10-SNAPSHOT' apply false
    id 'com.gradleup.shadow' version '8.3.+' apply false
}

allprojects {
    apply plugin: 'java'

    version = project.mod_version
    group = project.maven_group

    repositories {
        // Add repositories to retrieve artifacts from in here.
        // You should only use this when depending on other mods because
        // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        // ensure that the encoding is set to UTF-8, no matter what the system default is
        // this fixes some edge cases with special characters not displaying correctly
        // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
        // If Javadoc is generated, this must be specified in that task too.
        it.options.encoding = "UTF-8"
    }

    java {
        archivesBaseName = project.mod_id
        // If you remove this line, sources will not be generated.
        withSourcesJar()
    }
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'

    configurations {
        common {
            canBeResolved = true
            canBeConsumed = false
        }
    }

    dependencies {
        // To change the versions see the gradle.properties file
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        mappings loom.officialMojangMappings()
        include(implementation(common("blue.endless:jankson:1.2.3"))) // what (idk it works tho)
    }

    processResources {
        def properties = [
                version          : project.version,
                minecraft_version: project.minecraft_version,
                mod_id           : project.mod_id,
                mod_name         : project.mod_name,
                mod_description  : project.mod_description
        ]

        inputs.properties properties
        filteringCharset "UTF-8"

        filesMatching(["fabric.mod.json", "META-INF/*mods.toml"]) {
            expand properties
        }
    }

    loom {
        runs {
            configureEach {
                property 'mixin.debug.export', 'true'
                property 'mixin.debug.verbose', 'true'
            }
        }
    }

    jar {
        from("LICENSE") {
            rename { "${it}_${project.mod_id}" }
        }
    }
}