# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Loader Properties
# check these on https://fabricmc.net/develop/ and https://projects.neoforged.net/neoforged/neoforge
minecraft_version=1.21.1
fabric_loader_version=0.16.14
fabric_version=0.116.0+1.21.1
neoforge_version=21.1.173
# Mod Properties
mod_version=2.0.0
maven_group=dev.doublekekse
mod_id=boids
mod_name=Boids
mod_description=This mod replaces the vanilla fish behavior of flocking fish with a boids simulation.